#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using RoadRunnerTemplate.DataAccess;

namespace RoadRunnerTemplate.DataAccess	
{
	public partial class Barang
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _nama;
		public virtual string Nama
		{
			get
			{
				return this._nama;
			}
			set
			{
				this._nama = value;
			}
		}
		
		private decimal _hargaBeli;
		public virtual decimal HargaBeli
		{
			get
			{
				return this._hargaBeli;
			}
			set
			{
				this._hargaBeli = value;
			}
		}
		
		private decimal _hargaJual;
		public virtual decimal HargaJual
		{
			get
			{
				return this._hargaJual;
			}
			set
			{
				this._hargaJual = value;
			}
		}
		
		private int _kategoriID;
		public virtual int KategoriID
		{
			get
			{
				return this._kategoriID;
			}
			set
			{
				this._kategoriID = value;
			}
		}
		
		private int _lokasiID;
		public virtual int LokasiID
		{
			get
			{
				return this._lokasiID;
			}
			set
			{
				this._lokasiID = value;
			}
		}
		
		private Kategori _kategori;
		public virtual Kategori Kategori
		{
			get
			{
				return this._kategori;
			}
			set
			{
				this._kategori = value;
			}
		}
		
		private Lokasi _lokasi;
		public virtual Lokasi Lokasi
		{
			get
			{
				return this._lokasi;
			}
			set
			{
				this._lokasi = value;
			}
		}
		
		private IList<DetilPembelian> _detilPembelians = new List<DetilPembelian>();
		public virtual IList<DetilPembelian> DetilPembelians
		{
			get
			{
				return this._detilPembelians;
			}
		}
		
	}
}
#pragma warning restore 1591
