#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using RoadRunnerTemplate.DataAccess;

namespace RoadRunnerTemplate.DataAccess	
{
	public partial class DetilPembelian
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private int _barangID;
		public virtual int BarangID
		{
			get
			{
				return this._barangID;
			}
			set
			{
				this._barangID = value;
			}
		}
		
		private int _orderQty;
		public virtual int OrderQty
		{
			get
			{
				return this._orderQty;
			}
			set
			{
				this._orderQty = value;
			}
		}
		
		private int _pembelianID;
		public virtual int PembelianID
		{
			get
			{
				return this._pembelianID;
			}
			set
			{
				this._pembelianID = value;
			}
		}
		
		private Barang _barang;
		public virtual Barang Barang
		{
			get
			{
				return this._barang;
			}
			set
			{
				this._barang = value;
			}
		}
		
		private Pembelian _pembelian;
		public virtual Pembelian Pembelian
		{
			get
			{
				return this._pembelian;
			}
			set
			{
				this._pembelian = value;
			}
		}
		
	}
}
#pragma warning restore 1591
