#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using RoadRunnerTemplate.DataAccess;

namespace RoadRunnerTemplate.DataAccess	
{
	public partial class EntitiesModel : OpenAccessContext, IEntitiesModelUnitOfWork
	{
		private static string connectionStringName = @"RoadRunnerConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EntitiesModel.rlinq");
		
		public EntitiesModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public EntitiesModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public EntitiesModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public EntitiesModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public EntitiesModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Pembelian> Pembelians 
		{
			get
			{
				return this.GetAll<Pembelian>();
			}
		}
		
		public IQueryable<Lokasi> Lokasis 
		{
			get
			{
				return this.GetAll<Lokasi>();
			}
		}
		
		public IQueryable<Kategori> Kategoris 
		{
			get
			{
				return this.GetAll<Kategori>();
			}
		}
		
		public IQueryable<DetilPembelian> DetilPembelians 
		{
			get
			{
				return this.GetAll<DetilPembelian>();
			}
		}
		
		public IQueryable<Barang> Barangs 
		{
			get
			{
				return this.GetAll<Barang>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MsSql";
			backend.ProviderName = "System.Data.SqlClient";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of EntitiesModel.
		/// </summary>
		/// <param name="config">The BackendConfiguration of EntitiesModel.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IEntitiesModelUnitOfWork : IUnitOfWork
	{
		IQueryable<Pembelian> Pembelians
		{
			get;
		}
		IQueryable<Lokasi> Lokasis
		{
			get;
		}
		IQueryable<Kategori> Kategoris
		{
			get;
		}
		IQueryable<DetilPembelian> DetilPembelians
		{
			get;
		}
		IQueryable<Barang> Barangs
		{
			get;
		}
	}
}
#pragma warning restore 1591
