#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using RoadRunnerTemplate.DataAccess;

namespace RoadRunnerTemplate.DataAccess	
{
	public partial class Lokasi
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _nomorRak;
		public virtual string NomorRak
		{
			get
			{
				return this._nomorRak;
			}
			set
			{
				this._nomorRak = value;
			}
		}
		
		private string _nomorBay;
		public virtual string NomorBay
		{
			get
			{
				return this._nomorBay;
			}
			set
			{
				this._nomorBay = value;
			}
		}
		
		private IList<Barang> _barangs = new List<Barang>();
		public virtual IList<Barang> Barangs
		{
			get
			{
				return this._barangs;
			}
		}
		
	}
}
#pragma warning restore 1591
